---
- name: (nginx) check
  include_tasks: check_nginx.yml
  when: check_nginx | default(false) | bool

- name: (mysql) check
  include_tasks: check_mysql.yml
  when: check_mysql | default(false) | bool
